version: '3.8'
name: 'backend-jj'
services:
  mysql:
    build: ./SQL
    ports:
      - "33068:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: blog_password
      MYSQL DATABASE: blog_db
    volumes:
      - "mysql_data:/var/lib/mysql"
      
  api:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql

volumes:
   mysql_data:
     driver: "local"